---
- name: Copy Kafka config file 1
  copy:
    src: server-1.properties
    dest: /root/software/kafka_2.11-2.1.0/config
  when: ansible_enp0s3.ipv4.address == "192.168.0.102"
- name: Start kafka server 1
  command: /root/software/kafka_2.11-2.1.0/bin/kafka-server-start.sh -daemon /root/software/kafka_2.11-2.1.0/config/server-1.properties
  when: ansible_enp0s3.ipv4.address == "192.168.0.102"