---
- name: Copy Kafka config file 3
  copy:
    src: server-3.properties
    dest: /root/software/kafka_2.11-2.1.0/config
  when: ansible_enp0s3.ipv4.address == "192.168.0.104"
- name: Start kafka server 3
  command: /root/software/kafka_2.11-2.1.0/bin/kafka-server-start.sh -daemon /root/software/kafka_2.11-2.1.0/config/server-3.properties
  when: ansible_enp0s3.ipv4.address == "192.168.0.104"